import { MainData } from '../viewmodel/MainData';

export { mainData }

const mainData: MainData[] = [
  new MainData('Hello', true),
  new MainData('PageJump', true),
  new MainData('RankingDemo', false),
  new MainData('ToDoList', false),
  new MainData('ArkTSComponents', false),
  new MainData('TargetManagement', false),
  new MainData('SimpleVideo', false),
  new MainData('MultipleDialog', false),
  new MainData('AnimateRefresh', false),
  new MainData('WebComponent', false),
  new MainData('NewsDataArkTS', false),
]